// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');
const { ObjectId } = mongoose.Schema;

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    material: {
      type: ObjectId,
      ref: 'materials',
    },
    content: {
      type: String,
      default: '',
    },
    user: {
      type: ObjectId,
      ref: 'users',
    },
    like: {
      type: Number,
      default: 0,
    },
    sub_comments: [
      {
        content: {
          type: String,
          default: '',
        },
        user: {
          type: ObjectId,
          ref: 'users',
        },
        like: {
          type: Number,
          default: 0,
        },
      },
    ],
  }, {
    timestamps: false,
  });

  return mongoose.model('comments', schema, 'comments');
};
